### ISSUE TITLE
Protocols other than http and https not supported

### ISSUE THREAD

**Issue by MarkChrisLevy** [dlemstra/magick-wasm#158] opened 2024-03-22 14:25 UTC
### magick-wasm version

>=0.0.26

### Description

Since version 0.0.26 there is a restriction of web protocols, that can load wasm file - only http and https are supported. I couldn't find explanation why this restriction is needed, but in my case it is a problem when wasm is to be loaded in webview iOS app, with customized protocol (in my case is capacitor://). In apps like mine, the protocol differs depending of the platform - in web app it is https, but in case mobile hybrid app it can be http or capacitor (or any other defined by me).

### Steps to Reproduce

Load wasm in non http and https web protocol.

**Comment by dlemstra** [comment] 2024-03-22 18:32
I have no idea what is enforcing that restriction. Does it still work with older versions? What kind of error message are you getting? And is it possible to create something that can be used in Visual Studio or Rider to reproduce this issue?

**Comment by dlemstra** [comment] 2024-04-09 08:13
Closing this due to lack of information.

**Closed by dlemstra** 2024-04-09 08:13 UTC
